// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:188abbd9-33f2-4810-94e6-4a37d077fd80',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'popsimulatorhelper-hosting-mobilehub-464958672',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2qfjds1kfck4c.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"popsimulatorhelper-mobilehub-464958672-populationSimulatorInstructorConfigurationDetails","attributes":[{"name":"userId","type":"S"},{"name":"roomNumber","type":"S"},{"name":"googleFormUrl","type":"S"},{"name":"googleSheetUrl","type":"S"}],"indexes":[],"region":"us-east-1","hashKey":"userId","rangeKey":"roomNumber"}],
    'aws_mobile_analytics_app_id': '6369248c6fd8440586c7595b7abdb557',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'c3bce6fc-59f6-46a5-90bc-3878c76473c6',
    'aws_project_name': 'popsimulator_helper',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'popsimulatorhelper-mobilehub-464958672',
}

export default awsmobile;
